# fastapi_app.py
import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List
from enum import Enum

# Set up built-in logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger(__name__)

app = FastAPI(title="RAG Chatbot API")

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class JurisdictionEnum(str, Enum):
    india = "India"
    international = "International"

class Citation(BaseModel):
    source: str
    text: str

class QueryRequest(BaseModel):
    message: str = Field(..., min_length=2, max_length=1000)
    jurisdiction: JurisdictionEnum

class ChatResponse(BaseModel):
    answer: str
    citations: List[Citation]

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(request: QueryRequest):
    try:
        # Logging payload
        logger.info(f"Received request payload: {request.model_dump()}")
        
        message_lower = request.message.lower()

        # Simulated Error states for testing error handling
        if "fail db" in message_lower:
            raise Exception("chromadb connection error")
            
        if "fail llm" in message_lower:
            raise Exception("groq llm timeout")

        # RAG pipeline implementation goes here...
        
        return ChatResponse(
            answer="This is a response generated by the RAG pipeline. Note that this is a simulated FastAPI backend.",
            citations=[Citation(source="Example Source Document", text="Relevant excerpt from the document.")]
        )

    except Exception as e:
        error_str = str(e).lower()
        logger.error(f"Error processing chat request: {e}", exc_info=True)
        
        if "chromadb" in error_str:
            raise HTTPException(status_code=503, detail="Database connection failed.")
        elif "groq" in error_str or "timeout" in error_str:
            raise HTTPException(status_code=502, detail="Upstream LLM provider unavailable.")
        else:
            raise HTTPException(status_code=500, detail=str(e))
